// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhowuibcbwxfeyuwmhni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ob3d1aWJjYnd4ZmV5dXdtaG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4OTI1ODIsImV4cCI6MjA1NDQ2ODU4Mn0.lmKC_h5QX_6tDatkGMjTy_F2HIPZdQXOPNx4MygPRK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);